// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6442.Robot2018StartAgain.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6442.Robot2018StartAgain.Robot;
import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;

/**
 *
 */
public class Feed extends Command {

       public Feed() {

       }

    @Override
    protected void initialize() {
    	
    	//RobotMap.launcherLauncherStage1.set(1);
    	
    	
//    	System.out.println("Starting System 1");
    }

    @Override
    protected void execute() {
    }

   @Override
    protected boolean isFinished() {
        return true;
    }

   @Override
    protected void end() {
    }

    @Override
    protected void interrupted() {
    }
}
