// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6442.Robot2018StartAgain.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6442.Robot2018StartAgain.Robot;

/**
 *
 */
public class Grab extends Command {
	
	public Grab() {
    
		requires(Robot.grabber);

		requires(Robot.grabber);
    }

	@Override
    protected void initialize() {
    }

	@Override
    protected void execute() {
    	
    	int mode = Robot.controllerMode;
  	
    	
//    	if(mode == Robot.tankMode || mode == Robot.arcadeMode) { 
//    	double triggerLeft = Robot.oi.joystick.getRawAxis(2);
//    	double triggerRight = Robot.oi.joystick.getRawAxis(3);
    	double triggerLeft = Robot.oi.leftTrigger(1);
    	double triggerRight = Robot.oi.rightTrigger(1);
    	double speed = triggerRight-triggerLeft;
    	Robot.grabber.grab(speed);    	
//    	}
//    }else if(mode == 1){
//    		double joyLeft = Robot.oi.joystick.getRawAxis(1);
//        	double joyRight = Robot.oi.joystick.getRawAxis(5);
//        	Robot.grabber.grabAD(joyRight, joyLeft);
//        	
//    	}
    }
    
	@Override
    protected boolean isFinished() {
        return false;
    }

    @Override
    protected void end() {
    }

    @Override
    protected void interrupted() {
    }
}
