// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6442.Robot2018StartAgain.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6442.Robot2018StartAgain.Robot;
import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;

/**
 *
 */
public class LaunchDone extends Command {
	private double time;
	private Timer timer;

	public LaunchDone(double waitTime) {

    	time = waitTime;
    	timer = new Timer();
    	}
    	
        @Override
    protected void initialize() {
    	timer.start();
    	
    }

   @Override
    protected void execute() {
    	
    }

    @Override
    protected boolean isFinished() {
        return timer.get() > time;
        
    }

    @Override
    protected void end() {
    	System.out.println("Stoping Stage 1");
//    	RobotMap.launcherLauncherStage1Group.set(0);
    	System.out.println("Stoping Stage 2");
//    	RobotMap.launcherLauncherStage2Group.set(0);
    }

    @Override
    protected void interrupted() {
    }
}
