package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PowerDistributionPanel;

public class DistributionPanel extends Subsystem {

    private final PowerDistributionPanel powerDistributionPanel1 = RobotMap.distributionPanelPowerDistributionPanel1;

    @Override
    public void initDefaultCommand() {
    }

    @Override
    public void periodic() {
    }
}

