package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Ultrasonic;

public class DistanceSensor extends Subsystem {

    private final Ultrasonic ultrasonic1 = RobotMap.distanceSensorUltrasonic1;

    @Override
    public void initDefaultCommand() {

    }

    @Override
    public void periodic() {

    }


}

