package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.Robot;
import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

public class DriveTrain extends Subsystem {

    private final SpeedController driveRight = RobotMap.driveCtrlRight;
    private final SpeedController driveLeft = RobotMap.driveCtrlLeft;
    private final SpeedControllerGroup driveBoth = RobotMap.driveCtrlBoth;

    @Override
    public void initDefaultCommand() {
       setDefaultCommand(new AnalogDrive());
    }
    
    public void tankDrive(double rightMagnitude, double leftMagnitude) {
    	set(leftMagnitude, rightMagnitude);
    }
    
    public void set(double left, double right) {
    	driveLeft.set(left);  	
    	driveRight.set(right);
    }
    
    public void set(double value) {
    	set(value*Robot.values.leftDriveFrac, value*Robot.values.rightDriveFrac);	
    }
    
    public void forwardFull() {
    	set(1);
    }    
    
    public void forwardHalf() {
    	set(0.5);
    }
    
    public void rightTurn() {
    	set(-0.5, 0.5);
    }
    
    public void leftTurn() {
    	set(0.5,-0.5);
    }
    
    public void reverse() {
    	set(-0.5);
    }
    
    public void stop() {
    	set(0);
    }
    
    public void periodic() {
        // Put code here to be run every loop
    
    }
}

