// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.Robot;
import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController drive1 = RobotMap.driveTrainDrive1;//Right?
    private final SpeedController drive2 = RobotMap.driveTrainDrive2;//Left?
    private final SpeedControllerGroup speedControllerGroup1 = RobotMap.driveTrainSpeedControllerGroup1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        //Set the default command for a subsystem here.
       setDefaultCommand(new DriveCommand());
    }
    
    public void joyDrive(double rightMagnitude, double leftMagnitude) {

    	drive1.set(rightMagnitude);
    	drive2.set(leftMagnitude);
    	//System.out.println("joyDrive output:" + rightMagnitude + " " + leftMagnitude);
    }
    
    //realistically it would be driveForward(double speed, int time)
    //  drive1.set(speed);
    //  drive2.set(speed);
    //  do for(time);
    //  etc for rest of them
    
    public void forward() {

    	drive1.set(1);
    	drive2.set(1);
    	 
    	
    	//drive1.set(fracSpeed(rightMagnitude));
    	//drive2.set(fracSpeed(leftMagnitude));
//    	System.out.println("joyDrive output:" + rightMagnitude + " " + leftMagnitude);
    }
    public double fracSpeed(double speed) {
    	double speedFrac = Robot.prefs.getDouble("speedFrac", 1);
//    	return speedFrac * speed;
    	return speed;
    	
    	
    }
    
    
    public void autoDriveForward() {

    	drive1.set(.5);
    	drive2.set(.5);
    }
    public void rightTurn() {
    	drive1.set(-.5);
    	drive2.set(.5);
    }
    public void leftTurn() {
    	drive1.set(.5);
    	drive2.set(-.5);
    }
    public void reverse() {
    	drive1.set(-.5);
    	drive2.set(-.5);
    }
    public void stop() {
    	drive1.set(0);
    	drive2.set(0);
    }
    
    public void periodic() {
        // Put code here to be run every loop
    
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

