package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;


public class Launcher extends Subsystem {

	 private final SpeedController launcherStage1 = RobotMap.launcherLaunchStage1;
	 private final SpeedController launcherStage2 = RobotMap.launcherLaunchStage2;
//    private final SpeedController launchStage1R = RobotMap.launcherLaunchStage1R;
//    private final SpeedController launchStage1L = RobotMap.launcherLaunchStage1L;
//    private final SpeedControllerGroup launcherStage1Group = RobotMap.launcherLauncherStage1Group;
//    private final SpeedController launcherStage2R = RobotMap.launcherLauncherStage2R;
//    private final SpeedController launcherStage2L = RobotMap.launcherLauncherStage2L;
//    private final SpeedControllerGroup launcherStage2Group = RobotMap.launcherLauncherStage2Group;

    @Override
    public void initDefaultCommand() {
       // setDefaultCommand(new LauncherRaw());
    }

    @Override
    public void periodic() {
      
    	//when button pressed, launch?
    	//when button pressed, intake?

    }

    public void secure() {
    	
    }
    
    public void exchange() {
    	
    }
    
    public void feed() {
    	
    }

}

