package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

public class Launcher extends Subsystem {
	
	private final SpeedController launcher = RobotMap.launchCtrl;

    @Override
    public void initDefaultCommand() {
        //setDefaultCommand(new LauncherRaw());
    }

    public void set(double speed) {
    	launcher.set(speed);
    }
    
    public void launch(double speed) {
    	set(speed);
    }
    
    public void reverse() {
    	set(-0.5);
    }
    
    public void launchFast() {
    	set(1);
    }
    
    public void launchMed() {
    	set(0.5);
    }
    
    public void launchSlow() {
    	set(0.1);
    }
    
    public void stop() {
    	set(0);
    }
    
    @Override
    public void periodic() {
    	
    }
}

