package org.usfirst.frc6442.Robot2018StartAgain.subsystems;

import org.usfirst.frc6442.Robot2018StartAgain.Robot;
import org.usfirst.frc6442.Robot2018StartAgain.RobotMap;
import org.usfirst.frc6442.Robot2018StartAgain.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid;

public class Pneumatics extends Subsystem {

    private final Compressor compressor = RobotMap.pneumaticsCompressor;
    private final DoubleSolenoid doubleSolenoid = RobotMap.pneumaticsDoubleSolenoid;

    @Override
    public void initDefaultCommand() {
    	
    }
    
    public boolean compressorEnabled() {
    	return compressor.enabled();
    }
    
    public boolean compressorSwitch() {
    	return compressor.getPressureSwitchValue();
    }
    
    public double compressorCurrent() {
    	return compressor.getCompressorCurrent();
    }
    
    public void up() {
        if (doubleSolenoid != null) doubleSolenoid.set(DoubleSolenoid.Value.kForward);   
    }
    
    public void down() {
    	if (doubleSolenoid != null) doubleSolenoid.set(DoubleSolenoid.Value.kReverse);   
    } 
    
    public void off() {
    	if (doubleSolenoid != null) doubleSolenoid.set(DoubleSolenoid.Value.kOff);   
    }
    
    @Override
    public void periodic() {	

    }
}

